controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /index
    controller: App\Controller\ContactController::index
    methods: [GET]

list:
    path: /contact/list
    controller: App\Controller\ContactController::list
    methods: [GET]

add:
    path: /contact/add
    controller: App\Controller\ContactController::add
    methods: [GET, POST]